turtlebot_joy_teleop_node:  # Needs to be named after the node name. (The name is determined during node construction. Node name can be changed in launch file)
  ros__parameters:          # Needs to appear in the yaml file. this is standard ROS syntax

    # NOTES:
    # 1. 

    # joystick axes definitions
    joy_linear_x_axis: 1
    joy_angular_z_axis: 0

    # joystick button definitions
    arm_button: 0

    # turtlebot configurations
    always_armed: true
    max_linear_velocity: 0.22     # m/s
    max_angular_velocity: 2.84    # rad/s
    linear_acceleration: 0.5      # m/s^2
    angular_acceleration: 6.0       # rad/s^2
    publish_frequency: 20         # Hz




###################################### NOTES ###################################### 

# 1.   We can use 1 yaml file for several nodes by duplicatung the above standard structure and changing the node name. 
#     here is an example:
#     <Other_node_name>:
#       ros__parameters:
#         < variables>
#         ...
