turtlebot_teleop_node:
  ros__parameters:

  # joystick axes definitions
   joystick_lin_x_axis: 1
   joystick_ang_z_axis: 2

   # turtlebot configurations
   turtlebot_max_lin_vel: 0.22
   turtlebot_max_ang_vel: 2.84